project:
  type: website

website:
  title: MDR
  page-footer:
    left:
      - text: 'home >'
        href: '/'
    right:
      - text: LDM
        href: https://lucymcgowan.com
      - icon: github
        href: https://github.com/lucymcgowan/mdr-website
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/lucystats.bsky.social
format:
  html:
    fontcolor: '#CFE0E1'
    backgroundcolor: '#030303'
    linkcolor: '#38A6B7' # lex letter
    mainfont: 'Noto Sans Mono'
    theme: mdr.scss
    anchor-sections: false
    include-before-body:
      text: |
        <script> document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll(".spoiler").forEach(spoiler => {
         spoiler.addEventListener("click", function () {
            this.classList.toggle("revealed");
           });
          });
          });
         </script>


execute:
  freeze: true
