---
title: ""
format: 
  html:
    css: mdr.css
    include-after-body:
      text: <script type="text/javascript" src="card-animation.js"></script>
---


<center>


::: {.deck}

::: {.vertical-lines}
:::

::: {.vertical-lines}
:::

::: {.card style="--i: 0;"}

::: {.tab}
{{< fa home >}}
:::

::: {.card--front}

## welcome

we analyse data from the Severance TV show. please enjoy all analyses equally. 
[get your Lumon badge here >](join-us)

:::

::: {.card--back}  

## welcome

we analyse data from the Severance TV show. please enjoy all analyses equally. 
[get your Lumon badge here >](join-us)
:::

:::

::: {.card style="--i: 1;"}
::: {.tab}
A
:::

::: {.card--front}

## about

This site was built by Lucy D. 

[Read More >](about)
:::

::: {.card--back}  

## about

This site was built by Lucy D. 

[Read More >](about)

:::
:::

::: {.card style="--i: 2;"}
::: {.tab}
B
:::

::: {.card--front}

## B natural

Be natural Helly, or should I say *Helena*...an elevator ding analysis

[Read More >](analysis-b-natural)
:::

::: {.card--back}  

## B natural

Be natural Helly, or should I say *Helena*......an elevator ding analysis

[Read More >](analysis-b-natural)

:::
:::

::: {.card style="--i: 3;"}
::: {.tab}
D
:::

::: {.card--front}

## elevator ding analysis

`C#`, `G`, or `Bb`? the pitch alone tells the story.  
[Read More >](analysis-elevator-dings)

:::

::: {.card--back} 

## elevator ding analysis

`C#`, `G`, or `Bb`? the pitch alone tells the story.  
[Read More >](analysis-elevator-dings)

:::
:::

::: {.card style="--i: 4;"}
::: {.tab}
F
:::

::: {.card--front}

## how we're feeling

This analysis creates a little sentiment profile for each episode.

[Read More >](analysis-feeling-over-time)

:::

::: {.card--back} 

## how we're feeling

This analysis creates a little sentiment profile for each episode.

[Read More >](analysis-feeling-over-time)

:::
:::

::: {.card style="--i: 5;"}
::: {.tab}
H
:::

::: {.card--front}

## helly or helena?

Who is really on the severed floor?
[Read More >](analysis-helly-or-helena)


:::

::: {.card--back}  

## helly or helena?

Who is really on the severed floor?
[Read More >](analysis-helly-or-helena)


:::
:::

::: {.card style="--i: 6;"}
::: {.tab}
J
:::

::: {.card--front}

## join analysis

This analysis estimates when the employees joined Lumon based on their employee codes printed on their badges.

[Read More >](analysis-badges)
:::

::: {.card--back}  

## join analysis

This analysis estimates when the employees joined Lumon based on their employee codes printed on their badges.

[Read More >](analysis-badges)

:::
:::

::: {.card style="--i: 7;"}
::: {.tab}
L
:::

::: {.card--front}

## locker

What is going on with Mark's locker?  
[Read More >](analysis-locker)


:::

::: {.card--back}  

## locker

What is going on with Mark's locker?  
[Read More >](analysis-locker)


:::
:::

::: {.card style="--i: 8;"}
::: {.tab}
R
:::

::: {.card--front}

## check out our R package

[mdr](https://lucymcgowan.github.io/mdr/index.html)

:::

::: {.card--back}  

## check out our R package

[mdr](https://lucymcgowan.github.io/mdr/index.html)
:::
:::
    
    
::: {.card style="--i: 9;"}
::: {.tab}
S
:::

::: {.card--front}

## sentiment analysis

Who is happier: the innies or outies?    
[Read More >](analysis-innie-sentiment)


:::

::: {.card--back}  

## sentiment analysis

Who is happier: the innies or outies?    
[Read More >](analysis-innie-sentiment)


:::
:::

::: {.card style="--i: 10;"}
::: {.tab}
U
:::

::: {.card--front}

## uses too many big words?

Was Milchick's performance evaluation accurate?  
[Read More >](analysis-uses-too-many-big-words)


:::

::: {.card--back}  

## uses too many big words?

Was Milchick's performance evaluation accurate?  
[Read More >](analysis-uses-too-many-big-words)



:::
:::


::: {.card style="--i: 11;"}
::: {.tab}
W
:::

::: {.card--front}

## who's talking?

Check out these episode profiles color coded by who is speaking 
[Read More >](analysis-whos-talking)


:::

::: {.card--back}  

## who's talking?

Check out these episode profiles color coded by who is speaking 
[Read More >](analysis-whos-talking)


:::
:::





    


   
::: {.lines .right}
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span> 
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>  
:::

::: {.lines .left}
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
:::

:::
</center>


