---
format: html
---

<center>
::: text

## Who's talking?

This analysis was made possible by the [mdr](https://lucymcgowan.github.io/mdr) R package, which used data originally compiled by [the Severance wiki](https://severance.wiki/). For each episode we count the number of words each of the four main characters (Mark, Helly, Dylan, and Irving) speak for in each minute and visualize them below. Click on the tabs to switch episodes.
:::

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(tidytext)
library(ggiraph)
library(mdr)

make_plot <- function(input) {
data <- transcripts |>
  mutate(speaker = case_when(
         grepl("Cobel", speaker) ~ "Cobel",
         speaker == "Mark W" ~ "Mark W",
         grepl("Mark", speaker) ~ "Mark",
         grepl("Helly", speaker) ~ "Helly",
         speaker == "Dylan’s son" ~ "Dylan’s son",
         grepl("Dylan", speaker) ~ "Dylan",
         grepl("Irv", speaker) ~ "Irving",
         grepl("Devon", speaker) ~ "Devon",
         grepl("Ricken", speaker) ~ "Ricken",
         grepl("Milchick", speaker) ~ "Milchick",
         grepl("Burt", speaker) ~ "Burt",
         grepl("Petey", speaker) ~ "Petey",
         grepl("Casey | Gemma", speaker) ~ "Ms. Casey",
         grepl("Reghabi", speaker) ~ "Reghabi",
         TRUE ~ "other"
  ),
  id = glue::glue("Season {season} Episode {episode}")) |>
  filter(id == input) |>
  filter(speaker %in% c("Mark", "Helly", "Dylan", "Irving")) |>
  unnest_tokens(word, dialogue) |>
  mutate(minute = minute(timestamp)) |>
  group_by(id, minute, speaker) |>
  summarise(value = n(), .groups = 'drop') 

 ggplot(data) +
  geom_bar_interactive(aes(x = minute, y = value, fill = speaker,
                           tooltip = glue::glue("{minute} min<br>{speaker}: {value} words")), 
           stat = "identity") +
  scale_fill_manual(values = c("#EBCF00", "#A25056", "#00957E",  "#2358A8")) +
  theme_mdr() +
  theme(
    legend.position = "bottom",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    axis.line = element_blank(),
    plot.margin = unit(c(0, -0.63, 0, -0.63), "cm")
  ) +
  coord_radial(inner.radius = 0.2) +
  labs(fill = "")
}
```

::: {.panel-tabset}

## S1E1

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s1e1.png")

p <- make_plot("Season 1 Episode 1") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -45)

ggiraph::girafe(ggobj = p)

```

## S1E2

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s1e2.png")

p <- make_plot("Season 1 Episode 2") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -58)
ggiraph::girafe(ggobj = p)
```

## S1E3

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s1e3.png")

p <- make_plot("Season 1 Episode 3") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -50)
ggiraph::girafe(ggobj = p)
```

## S1E4

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s1e4.png")

p <- make_plot("Season 1 Episode 4") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -55)
ggiraph::girafe(ggobj = p)
```

## S1E5

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s1e5.png")

p <- make_plot("Season 1 Episode 5") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -32)
ggiraph::girafe(ggobj = p)
```

## S1E6

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s1e6.png")

p <- make_plot("Season 1 Episode 6") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -38)
ggiraph::girafe(ggobj = p)
```

## S1E7

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s1e7.png")

p <- make_plot("Season 1 Episode 7") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -45)
ggiraph::girafe(ggobj = p)
```

## S1E8

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s1e8.png")

p <- make_plot("Season 1 Episode 8") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -28)
ggiraph::girafe(ggobj = p)
```

## S1E9

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s1e9.png")

p <- make_plot("Season 1 Episode 9") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -45)
ggiraph::girafe(ggobj = p)
```

## S2E1

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s2e1.png")

p <- make_plot("Season 2 Episode 1") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -45)
ggiraph::girafe(ggobj = p)
```

## S2E2

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9
img <- data.frame(x = 0, y = 0, image = "s2e2.png")

p <- make_plot("Season 2 Episode 2") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -35)
ggiraph::girafe(ggobj = p)
```

## S2E3

```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 9

img <- data.frame(x = 0, y = 0, image = "s2e3.png")

p <- make_plot("Season 2 Episode 3") + 
    ggimage::geom_image(data = img, 
                        aes(x = x, y = y, image = image),
                        size = 0.15, nudge_x = -2, nudge_y = -33) 
ggiraph::girafe(ggobj = p)
```
:::

</center>
